export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_ING = "SET_ING";
export const FETCH_ING_ERR = "FETCH_ING_ERR";

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_ERROR = "PURCHASE_BURGER_ERROR";
